#!/bin/sh
. /opt/iredmail/docker-env

sed -i "s/TEMP_IREDADMIN_DB_PASSWD/$IREDADMIN_DB_PASSWD/" /opt/www/iredadmin/settings.py
sed -i "s/TEMP_IREDAPD_DB_PASSWD/$IREDAPD_DB_PASSWD/" /opt/www/iredadmin/settings.py
sed -i "s/TEMP_VMAIL_DB_ADMIN_PASSWD/$VMAIL_DB_ADMIN_PASSWD/" /opt/www/iredadmin/settings.py
sed -i "s/TEMP_MYSQL_SERVER_ADDRESS/$MYSQL_HOST/" /opt/www/iredadmin/settings.py
sed -i "s/999999999/$MYSQL_PORT/" /opt/www/iredadmin/settings.py

if [ ! -d /var/run/iredadmin ]; then
  mkdir /var/run/iredadmin
  chown iredadmin:iredadmin /var/run/iredadmin
  chmod 0755 /var/run/iredadmin
fi

# start - listens on tcp/7791
exec /usr/bin/uwsgi --ini /opt/www/iredadmin/rc_scripts/uwsgi/debian.ini --pidfile /var/run/iredadmin/iredadmin.pid
