#!/bin/sh

#  Load configuration values
. /opt/iredmail/docker-env
PIDFILE="/var/run/amavis/amavisd.pid"

if [ -e $PIDFILE ]; then
    if [ -e "/proc/$(cat $PIDFILE)/status" ]; then
        kill $(cat $PIDFILE)
    fi
fi

find /etc/amavis/conf.d -type f -exec sed -i "s/TEMP_MYSQL_SERVER_ADDRESS/$MYSQL_HOST/" {} \;
find /etc/amavis/conf.d -type f -exec sed -i "s/999999999/$MYSQL_PORT/" {} \;
find /etc/amavis/conf.d -type f -exec sed -i "s/TEMP_AMAVISD_DB_PASSWD/$AMAVISD_DB_PASSWD/" {} \;
find /etc/amavis/conf.d -type f -exec sed -i "s/HOSTNAME/${HOSTNAME}/g" {} \;
find /etc/amavis/conf.d -type f -exec sed -i "s/DOMAIN/${DOMAIN}/g" {} \;

# If the rsa key is missing, generate it
if [ ! -e /var/vmail/dkim/${DOMAIN}.pem ]; then
    echo "Generating DKIM..."
    if [ ! -d /var/vmail/dkim ]; then
        mkdir -p /var/vmail/dkim
        chmod 755 /var/vmail/dkim
    fi

    amavisd-new genrsa /var/vmail/dkim/${DOMAIN}.pem 2048
    chown amavis:amavis /var/vmail/dkim/${DOMAIN}.pem
    chmod 0400 /var/vmail/dkim/${DOMAIN}.pem
fi

# Creating symlink to RSA key
if [ ! -L /var/lib/dkim ]; then
    if [ -d /var/vmail/dkim ]; then
        mv /var/vmail/dkim/* /var/vmail/dkim/
        rm -r /var/vmail/dkim
    fi

    ln -s /var/vmail/dkim /var/lib/dkim
fi

exec /usr/sbin/amavisd-new foreground
