#!/bin/sh
echo "Starting amavisd..."

#  Load configuration values
. /opt/iredmail/docker-env

find /etc/amavis/conf.d -type f -exec sed -i "s/TEMP_MYSQL_SERVER_ADDRESS/$MYSQL_HOST/" {} \;
sed -i "s/TEMP_MYSQL_SERVER_ADDRESS/$MYSQL_HOST/" /opt/iredapd/settings.py /opt/www/iredadmin/settings.py
find /etc/amavis/conf.d -type f -exec sed -i "s/TEMP_MYSQL_SERVER_PORT/$MYSQL_PORT/" {} \;
sed -i "s/TEMP_MYSQL_SERVER_PORT/$MYSQL_PORT/" /opt/iredapd/settings.py /opt/www/iredadmin/settings.py
find /etc/amavis/conf.d -type f -exec sed -i "s/TEMP_AMAVISD_DB_PASSWD/$AMAVISD_DB_PASSWD/" {} \;
sed -i "s/TEMP_AMAVISD_DB_PASSWD/$AMAVISD_DB_PASSWD/" /opt/iredapd/settings.py /opt/www/iredadmin/settings.py
find /etc/amavis/conf.d -type f -exec sed -i "s/HOSTNAME/${HOSTNAME}/g" {} \;
find /etc/amavis/conf.d -type f -exec sed -i "s/DOMAIN/${DOMAIN}/g" {} \;

# If the rsa key is missing, generate it
if [ ! -e /var/lib/dkim/${DOMAIN}.pem ]; then
    echo "Generating DKIM..."
    amavisd-new genrsa /var/lib/dkim/${DOMAIN}.pem 2048
    chown amavis:amavis /var/lib/dkim/${DOMAIN}.pem
    chmod 0400 /var/lib/dkim/${DOMAIN}.pem
fi

exec /usr/sbin/amavisd-new foreground
