#!/bin/sh
PIDFILE="/var/run/amavis/amavisd.pid"

if [ -e $PIDFILE ]; then
    if [ -e "/proc/$(cat $PIDFILE)/status" ]; then
        kill $(cat $PIDFILE)
    fi
fi

#  Load configuration values
. /opt/iredmail/docker-env

# Set configuration values
find /etc/amavis/conf.d -type f -exec sed -i "s/TEMP_MYSQL_SERVER_ADDRESS/$MYSQL_HOST/" {} \;
find /etc/amavis/conf.d -type f -exec sed -i "s/999999999/$MYSQL_PORT/" {} \;
find /etc/amavis/conf.d -type f -exec sed -i "s/TEMP_AMAVISD_DB_PASSWD/$AMAVISD_DB_PASSWD/" {} \;
find /etc/amavis/conf.d -type f -exec sed -i "s/HOSTNAME/${HOSTNAME}/g" {} \;
find /etc/amavis/conf.d -type f -exec sed -i "s/DOMAIN/${DOMAIN}/g" {} \;

# Check user dkim folder
if [ ! -d /var/vmail/dkim ]; then
    mkdir -p /var/vmail/dkim
fi

# Fix dkim permissions
chmod 755 /var/vmail/dkim
chown amavis:amavis /var/vmail/dkim

# Creating symlink to RSA keys folder
if [ ! -L /var/lib/dkim ]; then
    if [ -d /var/lib/dkim ]; then
        mv /var/lib/dkim/* /var/vmail/dkim/
        chown amavis:amavis /var/vmail/dkim/*
        rm -r /var/lib/dkim
    fi

    ln -s /var/vmail/dkim /var/lib/
fi

# If the rsa key is missing, generate it
if [ ! -e /var/lib/dkim/${DOMAIN}.pem ]; then
    echo "Generating DKIM..."

    amavisd-new genrsa /var/vmail/dkim/${DOMAIN}.pem 2048
    chown amavis:amavis /var/vmail/dkim/${DOMAIN}.pem
    chmod 0400 /var/vmail/dkim/${DOMAIN}.pem
fi

exec /usr/sbin/amavisd-new foreground
