#!/bin/bash
echo "Starting spamd..."

PIDFILE=/var/run/spamd.pid
SPAMDOPTIONS="--create-prefs --max-children 5 --helper-home-dir"

# Stop already running Spamasssin instance
if [ -e $PIDFILE ]; then
    if [ -e "/proc/$(cat $PIDFILE)/status" ]; then
        kill $(cat $PIDFILE)
    fi
fi

# Start Spamassasin
/usr/sbin/spamd --pidfile $PIDFILE $SPAMDOPTIONS
