#!/bin/sh

# Configurations
. /opt/iredmail/docker-env
PROG='iredapd'
BINPATH='/opt/iredapd/iredapd.py'
PIDFILE='/var/run/iredapd.pid'

# Configure plugins
if [ ! -z "${IREDAPD_PLUGINS}" ]; then
  sed -i "/^plugins /c plugins = $IREDAPD_PLUGINS" /opt/iredapd/settings.py;
fi

check_status() {
    # Usage: check_status pid_number
    PID="${1}"
    l=$(ps -p ${PID} | wc -l | awk '{print $1}')
    if [ X"$l" = X"2" ]; then
        echo "running"
    else
        echo "stopped"
    fi
}

sed -i "s/TEMP_IREDAPD_DB_PASSWD/$IREDAPD_DB_PASSWD/" /opt/iredapd/settings.py
sed -i "s/TEMP_VMAIL_DB_BIND_PASSWD/$VMAIL_DB_BIND_PASSWD/" /opt/iredapd/settings.py
sed -i "s/TEMP_MYSQL_SERVER_ADDRESS/$MYSQL_HOST/" /opt/iredapd/settings.py
sed -i "s/99999/$MYSQL_PORT/" /opt/iredapd/settings.py

if [ -f ${PIDFILE} ]; then
  PID="$(cat ${PIDFILE})"
  s="$(check_status ${PID})"

  if [ X"$s" = X"running" ]; then
    echo "${PROG} is already running."
    kill -15 $PID
    rm -f ${PIDFILE} >/dev/null 2>&1
  else
    rm -f ${PIDFILE} >/dev/null 2>&1
  fi
fi


# Fix log to docker logs
if [ ! -d /var/log/iredapd ]; then
  mkdir -p /var/log/iredapd
  chown iredapd:iredapd /var/log/iredapd
  chmod 755 /var/log/iredapd
fi

ln -sf /proc/self/fd/2 /var/log/iredapd/iredapd.log

# Start iredapd
python ${BINPATH} --foreground
