#!/bin/sh

# Update RCB password
. /opt/iredmail/docker-env
sed -i "s/TEMP_RCM_DB_PASSWD/$RCM_DB_PASSWD/" \
    /opt/www/roundcubemail/config/config.inc.php \
    /opt/www/roundcubemail/plugins/password/config.inc.php
sed -i "s/TEMP_MYSQL_SERVER_ADDRESS/$MYSQL_HOST/" \
    /opt/www/roundcubemail/config/config.inc.php \
    /opt/www/roundcubemail/plugins/password/config.inc.php
sed -i "s/TEMP_MYSQL_SERVER_PORT/$MYSQL_PORT/" \
    /opt/www/roundcubemail/config/config.inc.php \
    /opt/www/roundcubemail/plugins/password/config.inc.php

# start php fpm
if [ ! -L /usr/sbin/php-fpm ]; then
  ln -s /usr/sbin/php-fpm7.3 /usr/sbin/php-fpm
fi

if [ ! -d /run/php ]; then
  mkdir -p /run/php
fi

exec /usr/sbin/php-fpm --nodaemonize
