#!/bin/sh

if [ ! -d /var/run/clamav ]; then
  mkdir -p /var/run/clamav
  chown clamav:root /var/run/clamav
  chmod 755 /var/run/clamav
fi

if [ ! -f /etc/cron.daily/freshclam ]; then
  echo "#!/bin/sh" >> /etc/cron.daily/freshclam
  echo "test -e /usr/bin/freshclam && /usr/bin/freshclam" >> /etc/cron.daily/freshclam
  chmod 755 /etc/cron.daily/freshclam
fi

exec /usr/sbin/clamd -F
