#!/bin/sh

. /opt/iredmail/docker-env
sed -i "s/TEMP_VMAIL_DB_ADMIN_PASSWD/${VMAIL_DB_ADMIN_PASSWD}/g" /opt/mlmmjadmin/settings.py
sed -i "s/TEMP_MYSQL_SERVER_ADDRESS/${MYSQL_HOST}/g" /opt/mlmmjadmin/settings.py
sed -i "s/99999/${MYSQL_PORT}/g" /opt/mlmmjadmin/settings.py

RS=$(echo $RANDOM | md5sum | awk '{print $1}')
sed -i "s/^api_auth_tokens.*$/api_auth_tokens = ['$RS']/g"  /opt/mlmmjadmin/settings.py
sed -i "s/^backend_api.*$/backend_api = 'bk_iredmail_sql'/g"  /opt/mlmmjadmin/settings.py

if [ ! -d /var/run/mlmmjadmin ]; then
  mkdir -p /var/run/mlmmjadmin
  chown mlmmj:mlmmj /var/run/mlmmjadmin
  chmod 0755 /var/run/mlmmjadmin
fi

# Fix log to docker logs
if [ ! -d /var/log/mlmmjadmin ]; then
  mkdir -p /var/log/mlmmjadmin
  chown mlmmj:mlmmj /var/log/mlmmjadmin
  chmod 755 /var/log/mlmmjadmin
fi

ln -sf /proc/self/fd/2 /var/log/mlmmjadmin/mlmmjadmin.log

exec /usr/bin/uwsgi --ini /opt/mlmmjadmin/rc_scripts/uwsgi/debian.ini --pidfile /var/run/mlmmjadmin/mlmmjadmin.pid
